### ISSUE TITLE
Adding a link to the github page at the end of page

### ISSUE THREAD

**Issue by Dostoi** [Continuities/adarkroom#198]
it could be nice to have the link to the github page at the end of the page to show to people that the game is open source or having a small text that mention it somewhere.

**Comment by skj3gg** [comment]
Added. Thanks again!

**Comment by Dostoi** [comment]
Can you add a link to play store version too ?

**Comment by skj3gg** [comment]
The official ADR android app has not been released yet.

**Comment by Dostoi** [comment]
So this app isn't related ?
https://play.google.com/store/apps/details?id=com.dragonstudio.adarkroom

**Comment by skj3gg** [comment]
It's an android clone of the web game that someone else did.

**Comment by Dostoi** [comment]
Ok I didn't know that.
