### ISSUE TITLE
Being able to buy medicine when there is a plague and you don't have enough

### ISSUE THREAD

**Issue by Dostoi** [Continuities/adarkroom#199]
I just had a plague and not enough medicine (only 2) to help cure but enough resources to buy the 3 medicines missing.
Is it possible to add an option to buy the amount of medicine needed in the dialogue ?

**Comment by skj3gg** [comment]
I think this is a good idea, will add it to the my list, unless you want to tackle it.

**Comment by Dostoi** [comment]
I don't have any coding knowledge sorry ^^

**Comment by skj3gg** [comment]
No problem, thanks for your contribution!
