### ISSUE TITLE
UX Improvement - prevent negative HP

### ISSUE THREAD

**Issue by Alex005** [Continuities/adarkroom#201]
When fighting various creatures on the Dusty Path, fights will be held, obviously. However when you for example, take a hit and deal an amount of damage higher than the enemy's health, their health moves into negative integers. **My suggestion is prevent the player from seeing the enemy's HP crossover into the negative numbers.** I think it's confusing (can you keep hitting if their health is < 0?) and unattractive (what do you mean they have negative health!?).

Two possible ideas would be to simply make the final hit only take their health to 0 and display "0/MaxHP", or add in some transition words to ease the player from low health to dead (not sure where that would fit).

**Comment by skj3gg** [comment]
Sounds about right. Feel free to add this, otherwise I'll get to it in time.
