### ISSUE TITLE
View Element Glitch

### ISSUE THREAD

**Issue by Anish-Agnihotri** [Continuities/adarkroom#207]
Alright, just got the source code and was testing out the code when I realized it had an Element Issue where as the player could simply change the code within the element to remove the wait time for the provoke fire button , etc. button to load.

The code originally (when waiting)
![code snip1](https://cloud.githubusercontent.com/assets/4398624/5687758/1df9c6d0-981e-11e4-9c4f-2f4b9913396b.PNG)
The code after (without waiting)
![code snip2](https://cloud.githubusercontent.com/assets/4398624/5687757/1df88d06-981e-11e4-9ba2-4b4f3643bfb5.PNG)

Notice the removal of the text : "disable" - if we were to type disable, we wouldn't have to wait for the button to load...

**Comment by Continuities** [comment]
There are a million and a half ways to cheat in ADR. The way I see it, people can play the game however they want. Doesn't hurt me none.

If they learn something about Javascript while cheating, I'd say it's a net positive.

**Comment by Anish-Agnihotri** [comment]
Oh , I thought the game was supposed to be hard... AH the wait burns!

**Comment by Continuities** [comment]
I've never personally thought of ADR as a hard game, though some have told
me that the Dusty Path is difficult. Regardless, timers never add to
difficulty, they just pace the experience.

**Comment by chuglydude** [comment]
Want me to fix that?

**Comment by skj3gg** [comment]
Nothing to fix

**Comment by Anish-Agnihotri** [comment]
Meh, I love this game the way it is although I was really pissed when I died because of a hidden  sniper on the dusty path... I HAD 2 IRON SWORDS! AHHHH

**Comment by skj3gg** [comment]
It stinks, but you'll be ok. :stuck_out_tongue:
