### ISSUE TITLE
switching the language resets timers

### ISSUE THREAD

**Issue by Gondlar** [Continuities/adarkroom#208]
When the language is switched, all timers are ready again which speeds up the game by a significant amount of time.

**Comment by skj3gg** [comment]
Right, like with #207, there is no prize for completing the game, so if someone wants to cheat themselves, it's no skin off my nose.

**Comment by daveschaefer** [comment]
@Gondlar Regardless of whether any changes are made to the game, using the language selection dialog to bypass the timers is a fantastically ingenius idea. Kudus to you for figuring it out. Any professional tester would be proud to have discovered a trick like that; keep up the great work ;)

**Comment by koralcem** [comment]
Don't know if it alters the resolution of this issue, but simply reloading the page resets all timers too. And you still get to keep all existing resources. Just FYI...
