### ISSUE TITLE
Migrating game state data by import is not working

### ISSUE THREAD

**Issue by koustuvsinha** [Continuities/adarkroom#214]
HI! First of all, thanks for this wonderful game. I have been trying to load my saved game data from the text it had generated to a different computer, but when I go to save->import and paste my code the game refreshes to start from the beginning. 

On closer ispection, the gameState LocalStorage key gets updated with saved values when I hit on import, but again after page refresh the localStorage key has the brand new game state. 
Source Environment : Ubuntu, Chrome latest
Target Environment : Windows 7, Chrome latest

**Comment by Continuities** [comment]
Sounds like a corrupted code. Can you paste your code here?

**Comment by koustuvsinha** [comment]
http://pastebin.com/wQHvwnis

**Comment by Continuities** [comment]
It looks like you accidentally pasted your code twice. Either that, or the
game doubled the export code for some weird reason...
Here is the corrected code: http://pastebin.com/xe59rTDv

**Comment by koustuvsinha** [comment]
ok! yeah now its working! thanks! :)
amazing game btw.. would love to contribute in it. where to start?

**Comment by Continuities** [comment]
There are plenty of issues in the issue list, if you'd like to tackle any
of those. Also, feel free to get creative and add content. Check out the
wiki for a place to start: https://github.com/Continuities/adarkroom/wiki
