### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by antoniro** [Continuities/adarkroom#237]
Hi i found a mistake in the english version of the game. After creating the workshop, several items are available to craft. One of them is an armor. It is written "Armour" instead of "Armor".

**Comment by Continuities** [comment]
"Armour" is correct. You are mistaken.

**Comment by oriramikad** [comment]
"Armor" is the American spelling. Everyone else spells it "armour".

**Comment by antoniro** [comment]
Sorry, my bad. I will close the issue. 
This game is wonderful! Keep up!

**Comment by Continuities** [comment]
Haha, it's okay!
