### ISSUE TITLE
Contributor Guidelines

### ISSUE THREAD

**Issue by Cogito** [Continuities/adarkroom#33]
I've made a start on a wiki page to help us standardise on how development can happen on this project. Would love feedback and extra info, especially from @Continuities 

https://github.com/Continuities/adarkroom/wiki/Contributing

**Comment by skj3gg** [comment]
I recently cleaned up the wiki, if anyone has any changes feel free to make them, or if there are any questions on the wiki and it's content, Please feel free you ask them.

I am closing this issue as I don't know what more we can add regarding contributor guidelines. Thanks for everyone's work on this effort.
