### ISSUE TITLE
State Manager / Engine.js big TODO

### ISSUE THREAD

**Issue by LucidCrux** [Continuities/adarkroom#45]
I needed to do this for content separation anyways, but it directly addresses the big TODO at the top of the engine file. I just wanted to post an issue before the weekend to hopefully make people aware of that so duplicate effort is not made. I have a lot of free time for a few days so I should hopefully get the first version done and integrated and ready for testing before too long. The first, starting commit is already up.

**Comment by skj3gg** [comment]
From what I can tell this was resolved already, so I'm removing the TODO.
